--DDL
--LENGUAJE DE DEFINICION DE DATOS:

--CREAR BASE DE DATOS:
CREATE DATABASE REUNION;
--USAMOS LA BASE DE DATOS:
GO
USE REUNION;

--CREAMOS LA TABLA CARGOS:
CREATE TABLE TBL_CARGOS(
	ICOD_CARGO INT NOT NULL IDENTITY,
	VDESC_CARGO VARCHAR(100),
	PRIMARY KEY (ICOD_CARGO)
);

--REGISTRO EN LA TABLA CARGOS:
INSERT INTO TBL_CARGOS(VDESC_CARGO) VALUES ('COORDINADOR DEL CURSO DE CIENCIAS DE LA COMPUTACION')
SELECT * FROM TBL_CARGOS;

--CREAMOS LA TABLA DOCENTES:
CREATE TABLE TBL_DOCENTES(
ICOD_DOCENTE INT NOT NULL IDENTITY,
VNOMBRE_DOCENTE VARCHAR(50),
VAPATERNO_DOCENTE VARCHAR(50),
VAMATERNO_DOCENTE VARCHAR(50),
FK_ICOD_CARGO INT NOT NULL,
PRIMARY KEY(ICOD_DOCENTE),
FOREIGN KEY (FK_ICOD_CARGO) REFERENCES TBL_CARGOS(ICOD_CARGO)
);
--REGISTRO EN LA TABLA DOCENTES:
INSERT INTO TBL_DOCENTES(VNOMBRE_DOCENTE,VAPATERNO_DOCENTE,VAMATERNO_DOCENTE,FK_ICOD_CARGO)
VALUES ('PEDRO', 'CARPIO','APELLIDO',1);
SELECT * FROM TBL_DOCENTES;

--CREAMOS LA TABLA ACTIVIDADES:
CREATE TABLE TBL_ACTIVIDADES(
ICOD_ACTIVIDAD INT NOT NULL IDENTITY,
VDESC_ACTIVIDAD VARCHAR(250),
PRIMARY KEY(ICOD_ACTIVIDAD)
--FK_ICOD_DOCENTE INT NOT NULL,
--FOREIGN KEY (FK_ICOD_DOCENTE) REFERENCES TBL_DOCENTES(ICOD_DOCENTE)
);
--AGREGAMOS LA COLUMNA FECHA DE ACTIVISADES EN LA TABLA ACTIVIDADES:
ALTER TABLE TBL_ACTIVIDADES
ADD DFEC_ACTIVIDAD DATE

--REGISTRO EN LA TABLA ACTIVIDADES:
INSERT INTO TBL_ACTIVIDADES(VDESC_ACTIVIDAD,DFEC_ACTIVIDAD)
VALUES ('REUNION CON DOCENTES','2019-01-01');
SELECT * FROM TBL_ACTIVIDADES;
-- GETDATE() USAREMOS PARA LA INSERCION DE HORA SALIDA Y ENTRADA

--CREAMOS LA TABLA REUNIONES:
CREATE TABLE TBL_REUNIONES(
ICOD_REUNION INT NOT NULL IDENTITY,
DFEC_REUNION DATE,
DHENT_REUNION DATE,
DHSAL_REUNION DATE,
VLUGAR_REUNION VARCHAR(50),
FK_ICOD_DOCENTE INT NOT NULL,
PRIMARY KEY(ICOD_REUNION),
FOREIGN KEY (FK_ICOD_DOCENTE) REFERENCES TBL_DOCENTES(ICOD_DOCENTE)
);

--MODIFICAMOS LA COLUMNA HORA DE ENTRADA Y SALIDA EN LA TABLA REUNIONES:
ALTER TABLE TBL_REUNIONES
ALTER COLUMN DHENT_REUNION DATETIME
ALTER TABLE TBL_REUNIONES
ALTER COLUMN DHSAL_REUNION DATETIME

--REGISTRO EN LA TABLA REUNIONES:
INSERT INTO TBL_REUNIONES(DFEC_REUNION,DHENT_REUNION,DHSAL_REUNION,VLUGAR_REUNION,FK_ICOD_DOCENTE)
VALUES ('2019-01-01',GETDATE(),NULL,'AUDITORIO OLLANTAYTAMBO',1);

UPDATE TBL_REUNIONES
SET DHENT_REUNION = GETDATE()
WHERE TBL_REUNIONES.ICOD_REUNION = 1;

SELECT * FROM TBL_REUNIONES;

--CREAMOS LA TABLA TEMAS:
CREATE TABLE TBL_TEMAS(
ICOD_TEMA INT NOT NULL IDENTITY,
VDESC_TEMA VARCHAR(500),
CEST_TEMA CHAR(1) DEFAULT '1',
FK_ICOD_ACTIVIDAD INT NOT NULL,
FK_ICOD_REUNION INT NOT NULL,
PRIMARY KEY(ICOD_TEMA),
FOREIGN KEY (FK_ICOD_ACTIVIDAD) REFERENCES TBL_ACTIVIDADES(ICOD_ACTIVIDAD),
FOREIGN KEY (FK_ICOD_REUNION) REFERENCES TBL_REUNIONES(ICOD_REUNION)
);

--REGISTRO EN LA TABLA TEMAS:
INSERT INTO TBL_TEMAS(VDESC_TEMA,FK_ICOD_ACTIVIDAD,FK_ICOD_REUNION)
VALUES ('REVISION DE FORMATOS',1,1);

SELECT * FROM  TBL_TEMAS;

--CREAMOS LA TABLA ASIGNADO:
CREATE TABLE TBL_ASIGNADO(
FK_ICOD_TEMA INT NOT NULL,
FK_ICOD_DOCENTE INT NOT NULL,
FOREIGN KEY (FK_ICOD_TEMA) REFERENCES TBL_TEMAS(ICOD_TEMA),
FOREIGN KEY (FK_ICOD_DOCENTE) REFERENCES TBL_DOCENTES(ICOD_DOCENTE)
);

ALTER TABLE TBL_ASIGNADO
ADD  DFEC_ASIGNADO DATE
--REGISTRO EN LA TABLA ASIGNADO
INSERT INTO TBL_ASIGNADO(FK_ICOD_TEMA,FK_ICOD_DOCENTE,DFEC_ASIGNADO)
VALUES (1,1,'2019-10-01');
SELECT * FROM  TBL_ASIGNADO;


--DML
--LENGUAJE DE MANIPULACIOND DE DATOS